name: 'Workflows'

on:
  push:

jobs:
  coding-standards:
    name: 'Coding Standards'
    uses: ./.github/workflows/phpcs.yml
  phpstan:
    name: 'Static Analysis'
    needs: [coding-standards]
    uses: ./.github/workflows/static-analysis.yml
  slic:
    name: 'PHP Tests'
    needs: [coding-standards, phpstan]
    uses: ./.github/workflows/php-tests.yml
